### ISSUE TITLE
Opening Railway Dashboard and using brush on rail always causes game instant crash

### ISSUE THREAD

**Issue by BoscoChung1234** [jonafanho/Minecraft-Transit-Railway#13]
**Expected Behaviour**
When opening railway dashboard and using brush on rail it shouldn't crash
**Actual Behaviour**
A clear and concise description of what actually happened.
Sometimes opening Railway Dashboard causes game to crash
Scheduling train always causes crash
**Reproduction Steps**
Steps to reproduce the behaviour:

1. idk

**Crash Report**
Attach a crash report to the issue.
[crash-2021-01-24_18.31.06-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5861988/crash-2021-01-24_18.31.06-client.txt)
**Screenshots**

**Environment**

- Minecraft Version: 1.16.4 (Test with both Canvas and Optifine, same result)
- Installed Mods: Phosphor, ModMenu, MiniUHD, OptiFabric, WorldEdit, REI, EasierCraft

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Hello, thank you for the detailed bug report. While I'm investigating this issue, do you mind only using the MTR mod, then adding in the mods one by one, to identify which mod causes it to crash? That would help too. Thanks.

**Comment by BoscoChung1234** [comment]
Hello. Another issue happened to the mod. After a train spawned it crashed for some reason and got the error
The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
Exit Code: -1

Every time when a train spawn after opening that world it instantlly crashes

Crash Report with only using Fabric API and MTR Mod:
[crash-2021-01-25_11.49.46-server.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5864042/crash-2021-01-25_11.49.46-server.txt)
Same result compared with using other mods, randomly crash if opening dashboard or using brush. Maybe a mod issue.

Also trains sometimes behave strange. Like it didn't stop at the end of the platform rail instead of stopping in the center or the start (Size is long enough and already added a normal trail at the end and the start). Sometimes trains spawn with missing parts.

MC World: 
[New World (7).zip](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5864055/New.World.7.zip)

Thanks for reading, looking forward for updates :)

**Comment by jonafanho** [comment]
Thanks for the new crash report and world download. I was able to reproduce the issue and I'm working on a fix.

**Comment by jonafanho** [comment]
This should be fixed in the beta-3 update. Please let me know if you encounter other issues, thanks!

**Comment by BoscoChung1234** [comment]
Hello. I've updated to the latest beta-3 version, looks like the problem is still unresolved. When I'm setting the train schedule the game crashed and gave me error Error: java.util.ConcurrentModificationException 
The game crashed whilst exception in server tick loop
Exit Code: -1

Crash report: 
[crash-2021-01-27_18.21.17-server.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5879427/crash-2021-01-27_18.21.17-server.txt)

Thanks for working on this problem hope it would be fixed

**Comment by jonafanho** [comment]
Sorry it's crashing again! I would suggest disabling phosphor and seeing if it works. I will also try to see if I can reproduce the issue.

Thanks for the other suggestions!

**Comment by jonafanho** [comment]
I also noticed that some of your mods are outdated, such as phosphor and the fabric loader itself. Try updating them and see.

**Comment by Eric28020** [comment]
Maybe you should upgrade Java JRE to 8u271 or 8u281.

**Comment by BoscoChung1234** [comment]
> I also noticed that some of your mods are outdated, such as phosphor and the fabric loader itself. Try updating them and see.

Thanks! Seems like it has been fixed.

**Comment by jonafanho** [comment]
Oh, it no longer crashes any more? That's great!

**Comment by BoscoChung1234** [comment]
Wait sorry, here's a sad update, after playing for some hours, I'm setting the schedule, then the crash came back again. Maybe I messed up something with the world, but here it is
[crash-2021-01-28_12.09.19-server.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5884720/crash-2021-01-28_12.09.19-server.txt)

Maybe it's already fixed a bit, the first hour worked well.

**Comment by jonafanho** [comment]
Ah, yes, those concurrent modification exceptions, they just come up randomly :(

I'll try to fix that in the future. For now, you can just relaunch the game. Sorry about that!

**Comment by Eric28020** [comment]
How am I supposed to fix this?
[hs_err_pid14384.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5909560/hs_err_pid14384.log)

**Comment by hapy2452354** [comment]
relaunching the game doesn't work for me, it still keeps crashing when i use items on platform rails

**Comment by hapy2452354** [comment]
The game crashed whilst rendering screen
Error: java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.class_437) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by the screen not calling super.init(Lnet/minecraft/client/MinecraftClient;II)V
Exit Code: 255

**Comment by jonafanho** [comment]
Hello, this is a known issue for Fabric API 0.30.0. Please use Fabric API 0.29.3. Thanks.

**Comment by jonathanqwq** [comment]
[hs_err_pid19196.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6095358/hs_err_pid19196.log)
the crash come again :(
java crashed

**Comment by jonathanqwq** [comment]
[minecraft-exported-logs-2021-03-05T16-44-01.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6095366/minecraft-exported-logs-2021-03-05T16-44-01.log)
[hs_err_pid6444.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6095367/hs_err_pid6444.log)

**Comment by Eric28020** [comment]
> [minecraft-exported-logs-2021-03-05T16-44-01.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6095366/minecraft-exported-logs-2021-03-05T16-44-01.log)
> [hs_err_pid6444.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6095367/hs_err_pid6444.log)

Maybe that might refer to #24.
